### ISSUE TITLE
Manual install: Uncaught ReferenceError: require is not defined const cheerio = require('cheerio')

### ISSUE THREAD

**Issue by MagTun** [raineorshine/memrise-export#5]
Hi, 

I would like to add a feature (export difficult words) to this extension so I tried to manually install it. But I can't make it run as there is an error with cheerio:

![image](https://user-images.githubusercontent.com/15843700/113481324-27964a00-9499-11eb-9ce6-68a0db0abced.png)

I don't know how to include Cheerio in the local extension as I could find a link to the script on the [cheerio](https://github.com/cheeriojs/cheerio#readme) repo. 

So my question is actually quite simple: how can I install this extension locally?

Thanks for you help and also thanks a lot for this extension!

**Comment by raineorshine** [comment]
Hi! Thanks for reaching out!

It looks like the instructions for manual installation were not updated since the move to CommonJS modules such as `cheerio`, which utilize `require`. `require` is built-in to NodeJS but is not supported by default in the browser. I use [browserify](http://browserify.org/) to make them work in the browser. You'll have to run the same build process to get it to work from source. I have the build script defined in the package file so it should be as simple as running two additional commands, `npm install` and `npm run build` in the repo directory.

Check out the [README](https://github.com/raineorshine/memrise-export) for the full, updated instructions and let me know if you have any difficulties!

**Comment by MagTun** [comment]
Thanks a lot for your quick reply and the updated instructions! 

I was able to add the "difficult words" feature, and if you are interested to add it to your extension, I created a pull request for it. 

An again, thanks for having created this extension, it really helps me in my learning journey!

**Comment by raineorshine** [comment]
Cool, I'll check it out!
